### ISSUE TITLE
Switch commenting to own hosted solution

### ISSUE THREAD

**Issue by lafriks** [go-gitea/blog#69]
One option could be: https://gitlab.com/commento/commento-ce

**Comment by tboerger** [comment]
* https://moot.it/
* https://github.com/sdqali/commentary
* https://github.com/phusion/juvia
* https://github.com/m2w/talaria
* https://github.com/posativ/isso
* https://github.com/talkatv/talkatv
* integrate our discourse forum, one thread per post

**Comment by tboerger** [comment]
Let's integrate our Discourse forum, it should work pretty straightforward: https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963

**Comment by lafriks** [comment]
Fixed by #71
